#ifndef DOORCTL_BTSTACK_CONFIG_H
#define DOORCTL_BTSTACK_CONFIG_H

#define ENABLE_LE_PERIPHERAL

// Memory config
#define HCI_ACL_PAYLOAD_SIZE 52
#define MAX_NR_HCI_CONNECTIONS 1
#define MAX_NR_L2CAP_SERVICES  2
#define MAX_NR_L2CAP_CHANNELS  2
#define MAX_NR_RFCOMM_MULTIPLEXERS 1
#define MAX_NR_RFCOMM_SERVICES 1
#define MAX_NR_RFCOMM_CHANNELS 1
#define NVM_NUM_LINK_KEYS  3

#endif //DOORCTL_BTSTACK_CONFIG_H