#ifndef DOORCTL_MBEDTLS_CONFIG_H
#define DOORCTL_MBEDTLS_CONFIG_H

#define MBEDTLS_SHA256_C
#define MBEDTLS_BASE64_C
#define MBEDTLS_BIGNUM_C

#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_C

#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_DP_SECP384R1_ENABLED
#define MBEDTLS_ECP_DP_SECP521R1_ENABLED
#define MBEDTLS_ECP_NIST_OPTIM

#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C

#define MBEDTLS_PEM_PARSE_C
#define MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG
#define MBEDTLS_PSA_CRYPTO_C
#define MBEDTLS_PK_C
#define MBEDTLS_OID_C
#define MBEDTLS_PK_PARSE_EC_EXTENDED
#define MBEDTLS_PK_PARSE_EC_COMPRESSED
#define MBEDTLS_PK_PARSE_C

#define MBEDTLS_ERROR_C

#endif //DOORCTL_MBEDTLS_CONFIG_H